### ISSUE TITLE
MPI related error

### ISSUE THREAD

**Issue by shashankg7** [shihaoji/wordrank#1]
Hi,

When I try to run the main executable of the code, I get the following error:

MPI multiple thread not provided!!! (2 != 3)

I am not sure what's wrong.

**Comment by shihaoji** [comment]
Please see the "Prerequisites" section of the readme file.
- MPI library, with multi-threading support (Intel MPI, MPICH2 or MVAPICH2)

You may be qualified to get a free copy at
https://software.intel.com/en-us/qualify-for-free-software

**Comment by oersted** [comment]
I fixed it by compiling OpenMPI on my own and doing `./configure --enable-mpi-thread-multiple`.

**Comment by tgalery** [comment]
@shihaoji maybe the fix above could be added to the readme

**Comment by chintler** [comment]
@shihaoji @oersted I purged OpenMPI that I had already installed, reinstalled OpenMPI from the following link's suggestions, and configured with  ./configure --enable-mpi-thread-multiple flag
https://www.open-mpi.org/faq/?category=building


Still can't get MPI to work, I get
    MPI multiple thread not provided!!! (2 != 3)


Any suggestions?
